---
# tasks file for elasticsearch-fluentd-kibana
- hosts: log_host_servers
  tasks:
    - include: ./tasks/prerequisites.yml
    - include: ./tasks/elasticsearch.yml
    - include: ./tasks/nginx.yml
    - include: ./tasks/kibana.yml
    - include: ./tasks/fluentd.yml
  handlers:
    - include: ./handlers/main.yml
