---
- name: Download Fluentd
  sudo: true
  get_url: url=http://packages.treasuredata.com/2/ubuntu/trusty/pool/contrib/t/td-agent/td-agent_2.0.4-0_amd64.deb dest=/tmp/td-agent_2.0.4-0_amd64.deb

- name: Install Fluentd
  sudo: true
  apt: deb=/tmp/td-agent_2.0.4-0_amd64.deb

- name: Start Fluentd
  sudo: true
  service: name=td-agent state=started enabled=yes

- command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-elasticsearch
- command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-record-reformer
- command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-record-modifier
