---
# tasks file for elasticsearch-fluentd-kibana
- hosts: log_host_servers
  vars:
    fluentd_plugins: []
    fluentd_sources: []
    fluentd_matches: []
  tasks:
    - include: install_prerequisites.yml
    - include: install_elasticsearch.yml
    - include: install_nginx.yml
    - include: configure_nginx.yml
    - include: install_kibana.yml
    - include: configure_kibana.yml
    - include: install_fluentd.yml
    - include: configure_fluentd.yml
  handlers:
    - include: ../handlers/main.yml

- hosts: log_client_servers
  vars:
    fluentd_plugins: []
    fluentd_sources: []
    fluentd_matches: []
  tasks:
    - include: install_fluentd.yml
    - include: configure_fluentd.yml
  handlers:
    - include: ../handlers/main.yml
