---
- name: Install Nginx
  sudo: true
  apt: pkg=nginx state=present

- name: Start Nginx
  sudo: true
  service: name=nginx state=started enabled=yes

- file: path=/var/log/nginx state=directory mode=0645
  sudo: true
