---
# handlers file for elasticsearch-fluentd-kibana
- name: start elasticsearch
  service: name=elasticsearch state=started

- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: start nginx
  service: name=nginx state=started

- name: restart nginx
  service: name=nginx state=restarted

- name: start fluentd
  service: name=td-agent state=started

- name: restart fluentd
  service: name=td-agent state=restarted
